---
title: "GFO604 Procesamiento de datos geográficos 2021-I"
author: 
- name: Manuel Vargas
  url: https://github.com/mfvargas
  affiliation: Universidad de Costa Rica
  affiliation_url: https://www.ucr.ac.cr/
- name: Christian Birkel
  affiliation: Universidad de Costa Rica
  affiliation_url: https://www.ucr.ac.cr/  
description: |
  Curso GF0604 Procesamiento de datos geográficos. Escuela de Geografía, Universidad de Costa Rica. Primer ciclo lectivo 2021.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Descripción
Este es un curso introductorio al procesamiento de datos geográficos mediante el lenguaje de programación [R](https://www.r-project.org/). Se imparte en la [Escuela de Geografía](https://www.geografia.fcs.ucr.ac.cr/) de la [Universidad de Costa Rica](https://www.ucr.ac.cr/).

Se estudian los fundamentos del lenguaje R, sus bibliotecas geoespaciales y sus capacidades para generar gráficos y modelos estadísticos. El enfoque del curso es teórico-práctico, con lecciones teóricas combinadas con ejercicios de programación en los cuales los estudiantes aplican en diversos escenarios de procesamiento de datos los conocimientos adquiridos. No se requieren conocimientos previos en programación de computadoras.

Este sitio web corresponde al curso impartido durante el primer ciclo lectivo de 2021. Para ver las versiones de otros ciclos lectivos, puede visitar el [sitio web general del curso](https://gf0604-procesamientodatosgeograficos.github.io/).

# Programa
[Programa del curso](https://github.com/gf0604-procesamientodatosgeograficos/2021i-programa/blob/main/gf0604-procesamientodatosgeograficos-g001-2021i.pdf)

# Lecciones
[01 Introducción al pensamiento computacional](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-01/)  
[02 Arquitectura de computadoras y lenguajes de programación](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-02/)  
[03 Interfaces de línea de comandos](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-03/)  
[04 El lenguaje de marcas Markdown](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-04/)  
[05 El sistema de control de versiones Git](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-05/)  
[06 El lenguaje de programación R - Conceptos básicos - RStudio, funciones, paquetes](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-06/)  
[07 El lenguaje de programación R - Conceptos básicos - tipos de datos](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-06/)  
[08 El lenguaje de programación R - Conceptos básicos - definición de funciones, condicionales](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-06/)  
[09 El lenguaje de programación R - Conceptos básicos - ciclos](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-06/)  
[10 Graficación con R - Introducción](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-10/)  
[11 Exploración de datos](https://github.com/gf0604-procesamientodatosgeograficos/2021i-datos/blob/main/hidrologia/fdc/FDC.csv)  
[12 Graficación con R - Gráficos de barras](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-10/)  
[13 Tidyverse](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-13/)  
[14 Graficación con R - Histogramas, gráficos de dispersión y otros](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-10/)  
[15 El ecosistema espacial de R - Datos vectoriales](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[16 El ecosistema espacial de R - Datos raster](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[17 Operaciones con datos de atributos - Datos vectoriales](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[18 Operaciones con datos de atributos - Datos raster](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[19 Operaciones con datos espaciales - Datos vectoriales](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[20 Ejercicio de procesamiento y visualización de datos geoespaciales (*Junco vulcani*)](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[21 Operaciones con datos espaciales - Datos raster](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[22 Ejercicio de procesamiento y visualización de datos geoespaciales (*Primates*)](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/)  
[23 Ejercicio de procesamiento y visualización de datos geoespaciales (*Primates*)](https://gf0604-procesamientodatosgeograficos.github.io/2021i-leccion-15/) 

# Tareas
[01 Markdown](https://gf0604-procesamientodatosgeograficos.github.io/2021i-tarea-01/)

# Recursos
[Recursos adicionales a la bibliografía del curso](recursos.html)